redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/sessions/tender-awesome-davinci/mnt/Safe TakeOff/STO-frontend/safetakeoff/safetakeoff/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/sessions/tender-awesome-davinci/mnt/Safe TakeOff/STO-frontend/safetakeoff"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"
VITE_BASE_PATH = "/"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]